---
- hosts: localhost
  connection: local
  tasks:
    - name: OSX Check homebrew is installed
      shell: "brew list"
      changed_when: False
      when: ansible_distribution == 'MacOSX'

    - name: OSX Install mongodb
      shell: "brew install mongodb"
      changed_when: False
      when: ansible_distribution == 'MacOSX'

    - name: OSX Install openssl
      shell: "brew install openssl"
      changed_when: False
      when: ansible_distribution == 'MacOSX'

    - name: OSX Start mongodb
      shell: "brew services start mongodb"
      changed_when: False
      when: ansible_distribution == 'MacOSX'

    - name: OSX Create self-signed SSL cert
      shell: 'openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=${ansible_fqdn}" -days 3650 -keyout /usr/local/etc/openssl/certs/outbit.key -out /usr/local/etc/openssl/certs/outbit.crt -extensions v3_ca creates=/usr/local/etc/openssl/certs/outbit.crt'
      when: ansible_distribution == 'MacOSX'

    - name: Linux Install mongodb and openssl
      package: name={{item}} state=installed
      when: ansible_distribution == 'Debian'
      with_items:
        - mongodb
        - openssl

    - name: Linux Start mongodb
      service: name=mongodb state=started enabled=yes
      when: ansible_distribution == 'Debian'

    - name: Linux Create self-signed SSL cert
      shell: 'openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=${ansible_fqdn}" -days 3650 -keyout /etc/ssl/localcerts/outbit.key -out /etc/ssl/localcerts/outbit.crt -extensions v3_ca creates=/etc/ssl/localcerts/outbit.crt'
      when: ansible_distribution == 'Debian'
