---
- hosts: localhost
  connection: local
  tasks:

    - name: OSX Install mongodb and openssl
      homebrew: name={{item}} state=installed
      when: ansible_distribution == 'MacOSX'
      with_items:
        - mongodb
        - openssl

    - name: OSX Start mongodb
      shell: "brew services start mongodb"
      changed_when: False
      when: ansible_distribution == 'MacOSX'

    - name: OSX Check if SSL cert exists
      always_run: yes
      changed_when: False
      stat: path=/usr/local/etc/openssl/certs/outbit.crt
      register: st
      when: ansible_distribution == 'MacOSX'

    - name: OSX Create self-signed SSL cert
      shell: 'openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN={{ansible_fqdn}}" -days 3650 -keyout /usr/local/etc/openssl/certs/outbit.key -out /usr/local/etc/openssl/certs/outbit.crt -extensions v3_ca'
      when: ansible_distribution == 'MacOSX' and st.stat.exists == False

    - name: Linux Install mongodb and openssl
      package: name={{item}} state=installed
      when: ansible_distribution == 'Debian'
      with_items:
        - mongodb
        - openssl

    - name: Linux Start mongodb
      service: name=mongodb state=started enabled=yes
      when: ansible_distribution == 'Debian'

    - name: Linux Check if SSL cert exists
      stat: path=/etc/ssl/private/outbit.crt
      always_run: yes
      changed_when: False
      register: st
      when: ansible_distribution == 'Debian'

    - name: Linux Create self-signed SSL cert
      shell: 'openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN={{ansible_fqdn}}" -days 3650 -keyout /etc/ssl/private/outbit.key -out /etc/ssl/private/outbit.crt -extensions v3_ca'
      when: ansible_distribution == 'Debian' and st.stat.exists == False
