language: python
# Version to Test Against
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

# Install Dependencies
install:
    - pip install nose
    - pip install pyyaml
    - pip install Flask
    - pip install requests
    # Coveralls 4.0 doesn't support Python 3.2
    - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
    - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi

# Run Tests
script:
    - 'export PYTHONPATH="${PYTHONPATH}:./lib"'
    - "coverage run --source=outbit $(which nosetests) -w test/units/"

after_success:
    - coveralls
