language: python
# Version to Test Against
python:
  #- "2.6"
  - "2.7"
  #- "3.3"
  #- "3.4"

# Install Dependencies
install:
    - pip install nose
    - pip install pyyaml
    - pip install Flask
    - pip install requests
    - pip install pymongo
    - pip install ply
    - pip install pycrypto
    - pip install coveralls
    - pip install mock
    - pip install mongomock
    - pip install requests-mock
    - pip install ldap3

# Run Tests
script:
    - './run_tests.sh'

after_success:
    - coveralls
